name: Enviar meme aleatório

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  rodar-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Instalar uv
        uses: astral-sh/setup-uv@v3
      - name: Rodar script
        run: uv run parser.py
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}